x-common: &common-config
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "5"

services:
  vincent:
    <<: *common-config
    image: 0xii/vincent:0.0.1
    ports:
      - "3000:3000"

  vincent-docs:
    <<: *common-config
    image: 0xii/vincent-docs:0.0.1
    ports:
      - "8080:8080"
